### ISSUE TITLE
Bug when loading with configurable

### ISSUE THREAD

**Issue by ingenstelum** [Bawnorton/Configurable#4]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-09-15 10:33:44
Description: Bootstrap

java.lang.ExceptionInInitializerError
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:52)
	at net.minecraft.client.main.Main.main(Main.java:130)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1665 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2246.method_45453(class_2246.java:121)
	at net.minecraft.class_2246.<clinit>(class_2246.java:395)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [bettertrims.mixins.json:attributes.projectile_dodge_chance.PersistentProjectileEntityMixin from mod bettertrims] from phase [DEFAULT] in config [bettertrims.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @WrapOperation operation wrapper method net/minecraft/class_1665::applyProjectileDodgeChance from bettertrims.mixins.json:attributes.projectile_dodge_chance.PersistentProjectileEntityMixin from mod bettertrims has an invalid signature. Found unexpected argument type org.spongepowered.asm.mixin.injection.callback.CallbackInfo at index 3, expected net.minecraft.class_3966. Handler signature: (Lnet/minecraft/class_1297;ILcom/llamalad7/mixinextras/injector/wrapoperation/Operation;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V Expected signature: (Lnet/minecraft/class_1297;ILcom/llamalad7/mixinextras/injector/wrapoperation/Operation;Lnet/minecraft/class_3966;)V
	at org.spongepowered.asm.mixin.injection.code.Injector.validateParams(Injector.java:614)
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjector.invokeHandler(WrapOperationInjector.java:126)
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjector.wrapOperation(WrapOperationInjector.java:91)
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjector.inject(WrapOperationInjector.java:47)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at com.llamalad7.mixinextras.injector.MixinExtrasLateInjectionInfo.lateInject(MixinExtrasLateInjectionInfo.java:52)
	at com.llamalad7.mixinextras.injector.LateInjectionApplicatorExtension.postApply(LateInjectionApplicatorExtension.java:40)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.postApply(TargetClassContext.java:433)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:405)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 15 more

**Comment by Bawnorton** [comment]
This is caused by better trims not configurable, also please send the whole log/crash report, not just the crash.

**Comment by ingenstelum** [comment]
Thank you
