### ISSUE TITLE
[Edited]

### ISSUE THREAD

**Issue by shotadft** [Bawnorton/Configurable#6]
I would like you to release a mojmap-compatible version for the latest version, because some problems are occurring with yarn.

**Comment by Bawnorton** [comment]
That error doesn't tell me anything other than "you disconnected". Please send the client and server latest.log, users should not be affected by the mappings

**Comment by shotadft** [comment]
`
---- Minecraft Network Protocol Error Report ----
// Abort, Retry, Ignore?

Time: 2024-10-22 00:11:26
Description: Packet handling error

io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: 接続が相手からリセットされました


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Epoll Server Play IO #2
Stacktrace:
	at knot//net.minecraft.class_2547.method_55622(class_2547.java:33)
Mixins in Stacktrace: None found

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Paper
Stacktrace:
	at knot//net.minecraft.class_2547.method_55622(class_2547.java:33)
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:62)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:136)
	at knot//net.minecraft.class_8673.method_60881(class_8673.java:127)
	at knot//net.minecraft.class_2535.exceptionCaught(class_2535.java:161)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at knot//io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at knot//io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at knot//io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at knot//io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at knot//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:728)
	at knot//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:826)
	at knot//io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at knot//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at knot//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at knot//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at knot//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Mixins in Stacktrace:
	net.minecraft.class_2600:
		gg.essential.mixins.transformers.compatibility.vanilla.Mixin_FixPacketHandlingPastServerShutdown (mixins.essential.json)
	net.minecraft.class_8673:
		net.fabricmc.fabric.mixin.networking.client.ClientCommonNetworkHandlerMixin (fabric-networking-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.ClientCommonNetworkHandlerAccessor (fabric-networking-api-v1.client.mixins.json)
		lol.bai.badpackets.impl.mixin.client.AccessClientCommonPacketListenerImpl (badpackets.mixins.json)
		gg.essential.mixins.transformers.client.network.Mixin_SendChatEvents (mixins.essential.json)
		lol.bai.badpackets.impl.mixin.client.MixinClientCommonPacketListenerImpl (badpackets.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinClientPacketListener (mixins/common/nochatreports.mixins.json)
	net.minecraft.class_2535:
		gg.essential.mixins.transformers.feature.ice.common.Mixin_IceChannelIsNotLocal (mixins.essential.json)
		net.fabricmc.fabric.mixin.networking.ClientConnectionMixin (fabric-networking-api-v1.mixins.json)
		me.steinborn.krypton.mixin.shared.network.pipeline.compression.ClientConnectionMixin (krypton.mixins.json)
		me.steinborn.krypton.mixin.shared.network.pipeline.encryption.ClientConnectionMixin (krypton.mixins.json)
		com.ishland.vmp.mixins.networking.eventloops.MixinClientConnection (vmp.mixins.json)
		gg.essential.mixins.transformers.client.network.Mixin_LogExceptions (mixins.essential.json)
		com.ishland.vmp.mixins.networking.avoid_deadlocks.MixinClientConnection (vmp.mixins.json)
		com.noxcrew.noxesium.mixin.settings.PacketExceptionMixin (noxesium.mixins.json)
		com.ishland.vmp.mixins.access.IClientConnection (vmp.mixins.json)
		gg.essential.mixins.transformers.client.network.Mixin_RedirectToLocalConnection (mixins.essential.json)
		dzwdz.chat_heads.mixin.ConnectionMixin (chat_heads.mixins.json)
		com.ishland.vmp.mixins.networking.no_flush.MixinClientConnection (vmp.mixins.json)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.8.0-47-generic
	Java Version: 21.0.5, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1136118624 bytes (1083 MiB) / 1824522240 bytes (1740 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: 2nd Generation Core Processor Family Integrated Graphics Controller
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x0116
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 7993.16
	Virtual memory used (MiB): 5756.46
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 16034.68, total: 46763.72
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 16034.68, total: 46763.72
	Space in storage for io.netty.native.workdir (MiB): available: 16034.68, total: 46763.72
	Space in storage for java.io.tmpdir (MiB): available: 16034.68, total: 46763.72
	Space in storage for workdir (MiB): available: 16034.68, total: 46763.72
	JVM Flags: 9 total; -Xmx4096M -XX:MaxNewSize=1G -XX:MetaspaceSize=1G -XX:MaxMetaspaceSize=1G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:+DisableExplicitGC
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.2.5
		animatica: Animatica 0.6.1+1.21
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		axolotlbuckets: Axolotl Buckets 1.2.0
		badoptimizations: BadOptimizations 2.1.4
		badpackets: Bad Packets 0.8.1
		balm-fabric: Balm 21.0.20
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		betterclouds: Better Clouds 1.7.4+1.21-fabric
		betterf3: BetterF3 11.0.2
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		bettermounthud: Better Mount HUD 1.2.4
		blur: Blur+ (Fabric) 5.0.0
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.291+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.291+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.291+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.291+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.291+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.291+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.291+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-dfc: Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.291+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.291+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.291+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.291+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.291+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.291+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.291+1.21.1
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		capes: Capes 1.5.4+1.21
		caramelchat: caramelChat 1.2.0
		chat_heads: Chat Heads 0.13.3
		chatanimation: ChatAnimation 1.0.6
		cherishedworlds: Cherished Worlds 10.0.2+1.21.1
		citresewn: CIT Resewn 1.2.2+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.2+1.21
		clean-debug: Clean F3 0.4.7
		clear-despawn-reworked: Clear Despawn Reworked 1.0.1
		clientsidenoteblocks: ClientSideNoteblocks 2.8
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		compact-chat: Compact Chat 2.1.1
		configurable: Configurable 2.1.2
		continuity: Continuity 3.0.0-beta.5+1.21
		craftpresence: CraftPresence 2.5.1
		ctrl-q: Ctrl Q 1.9
		cubes-without-borders: Cubes Without Borders 2.1.1+1.21
		debugify: Debugify 1.21.1+1.0
		dynamic_fps: Dynamic FPS 3.7.3
			net_lostluma_battery: battery 1.1.0
		dynamictrim: Dynamic-Trim 2.0.0
		eatinganimationid: Eating Animation 1.21+1.9.72
		elementa: Elementa 665
		emojitype: Emoji Type 2.2.7-1.21.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.1.0+1.21
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		essential: Essential 1.3.4.1
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		f3teverywhere: F3+T Everywhere 1.0.1
		fabric-api: Fabric API 0.106.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+83a9d31319
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.21+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.0+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df36019
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fabrishot: Fabrishot 1.14.1
		fastipping: Fast IP Ping 1.0.5
		fastquit: FastQuit 3.0.0+1.20.6
		ferritecore: FerriteCore 7.0.1
		feytweaks: FeyTweaks 1.21-1.2.8
		fsb-interop: FabricSkyBoxes Interop 1.4.0+mc1.21-build.54
		fusion: Fusion 1.1.1
		fzzy_config: Fzzy Config 0.5.4+1.21
			blue_endless_jankson: jankson 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		geckolib: GeckoLib 4 4.6.6
		highlight: Highlight 3.0.0
			resourcefullib: Resourceful Lib 3.0.1
				com_teamresourceful_bytecodecs: bytecodecs 1.1.0
				com_teamresourceful_yabn: yabn 1.0.3
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		keybind_fix: Keybind Fix 1.0.1
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		languagereload: Language Reload 1.6.1+1.21
		lithium: Lithium 0.14.0-snapshot+mc1.21.1-build.88
		macos_input_fixes: MacOS Input Fixes 1.7
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		mc122477fix: Mc122477Fix 1.1.0+mc1.20.5-1.21.1
		mc229142fix: MC229142Fix 1.0
		midnightcontrols: MidnightControls 1.10.0-beta.1
			obsidianui: ObsidianUI 0.2.7+mc1.21
			org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		midnightlib: MidnightLib 1.6.3
		minecraft: Minecraft 1.21.1
		mixintrace: MixinTrace 1.1.1+1.17
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.3
		morechathistory: More Chat History 1.3.1
		moreculling: More Culling 1.0.0
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		mousetweaks: Mouse Tweaks 2.26
		nbt_ac: NBT Autocomplete 1.3.6
		nbt_copy: NBT Copy 1.0.3
		netherportalfix: NetherPortalFix 21.1.1
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		notenoughanimations: NotEnoughAnimations 1.7.6
		notenoughcrashes: Not Enough Crashes 4.4.8+1.21
		noxesium: Noxesium 2.3.3+d22848f
			com_noxcrew_noxesium_api: api 2.3.3+d22848f
			org_khelekore_prtree: prtree 1.5
		optigui: OptiGUI 2.3.0-beta.6+1.21
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		org_jetbrains_annotations: annotations 23.0.0
		packetfixer: Packet Fixer 1.4.1
		particle_core: Particle Core 0.2.4+1.21
		placeholder-api: Placeholder API 2.4.1+1.21
		polymorph: Polymorph 1.0.6+1.21.1
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		polytone: Polytone 1.21-2.4.26
		puzzle: Puzzle 2.0.1
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.4+mc1.21.1
		roughlyenoughitems: Roughly Enough Items 16.0.783
			error_notifier: Error Notifier 1.0.11
		roughlyenoughprofessions: Roughly Enough Professions 4.0.3
		roughlysearchable: Roughly Searchable 2.8.0+1.21
		runtimetrims: RuntimeTrims 1.0.4
		shiftscrollfix: Shift-Scroll Fix 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21.1
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0-beta.3+mc1.21.1
		sodiumdynamiclights: Sodium Dynamic Lights 1.0.9
			forgeconfigapiport: Forge Config API Port 21.1.0
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
		sodiumleafculling: Sodium Leaf Culling 1.0.0
		sodiumoptionsapi: Sodium Options API 1.0.2
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sspb: Sodium Shadowy Path Blocks 4.0.0-beta.1
		status-effect-bars: Status Effect Bars 1.0.6
		superbettergrass: SuperBetterGrass 1.5.3+1.21
		telepistons: Telepistons 1.1.3
		threadtweak: ThreadTweak 0.1.5+mc1.21.1
		titlefixer: Title Fixer 1.0+1.21
		tooltipfix: ToolTip Fix 1.1.1-1.20
		unilib: UniLib 1.0.3
		universalcraft: UniversalCraft 362
		vigilance: Vigilance 306
		vmp: Very Many Players 0.2.0+beta.7.168+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
		waveycapes: WaveyCapes 1.4.10
		xaerominimap: Xaero's Minimap 24.5.0
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Loaded Shaderpack: (off)
	Suspected Mods: None
`

**Comment by Bawnorton** [comment]
Well this crash report doesn't actually have anything useful in it. Basically all the info is about how the crash is handled and not the crash itself. 

I don't think this is related to configurable, but just to confirm, here's the mojmap equivalent jar from the maven https://maven.bawnorton.com/releases/com/bawnorton/configurable/configurable-fabric-mojmap/2.1.2+1.21.1/configurable-fabric-mojmap-2.1.2+1.21.1.jar

**Comment by shotadft** [comment]
I changed to mojmap but the situation did not change. I guess I was looking in the wrong place.
Thank you very much for responding so late at night.
